metrics_enabled: false
debug: true
graphite:
  host: carbon.hostedgraphite.com
  api_key: 7509c0ff-4db5-4cae-91ee-6e78ff13b336
  reporting_interval_in_seconds: 30
  include_metrics:
    - com.hello


common_db:
  driverClass: org.postgresql.Driver

  user: ingress_user
  password: hello ingress user
  url: jdbc:postgresql://chanku-test.cdawj8qazvva.us-east-1.rds.amazonaws.com:5432/chanku

  properties:
    hibernate.dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"

  initialSize: 2

  # the minimum number of connections to keep open
  minSize: 2

  # the maximum number of connections to keep open
  maxSize: 8

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  # how long a connection must be held before it can be validated
  evictionInterval: 10s

  # the maximum lifetime of an idle connection
  minIdleTime: 1 minute

sensors_db:
  driverClass: org.postgresql.Driver

  # use prod_sense_data on redshift
  user: suripu_queue
  password: Hello-suripu-queue-123
  url: jdbc:postgresql://sensors2.cy7n0vzxfedi.us-east-1.redshift.amazonaws.com:5439/sensors1


  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"

  initialSize: 2

  # the minimum number of connections to keep open
  minSize: 2

  # the maximum number of connections to keep open
  maxSize: 8

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  # how long a connection must be held before it can be validated
  evictionInterval: 10s

  # the maximum lifetime of an idle connection
  minIdleTime: 1 minute

server:
  adminMinThreads: 1
  adminMaxThreads: 10
  adminContextPath: /
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 8118
      idleTimeout: 25 seconds
  adminConnectors:
    - type: http
      port: 8008
      idleTimeout: 25 seconds

# Logging settings.
logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO
  loggers:
    # Logger-specific levels, e.g. sets the level for 'com.hello.suripu.queue' to DEBUG.
    com.hello.suripu: INFO
    com.hello.suripu.queue: DEBUG
    com.hello.suripu.core: WARN
    com.hello.suripu.coredw: WARN
    com.hello.suripu.algorithm: WARN
  appenders:
    - type: file
      threshold: DEBUG
      currentLogFilename: /var/log/suripu-queue/suripu-queue.log
      archivedLogFilenamePattern: /var/log/suripu-queue/suripu-queue-%d{yyyy-MM-dd}.log.gz
      archivedFileCount: 7

sleep_stats_version: v_0_2

timeline_model_ensembles:
  bucket: hello-timeline-models
  key: normal4ensemble.base64

timeline_seed_model:
  bucket: hello-timeline-models
  key: normal4.base64

taimurain_configuration:
   http_client_config:
     keepAlive: 0s
     timeout: 10000ms
   endpoints:
     neural_net : http://internal-taimurain-230356525.us-east-1.elb.amazonaws.com:80
     neural_net_four_event: http://ec2-54-224-150-186.compute-1.amazonaws.com:5557

SQS_configuration:
    sqs_queue_name: dev_timeline_queue
    sqs_max_connections: 50
    sqs_max_messages_read: 10
    sqs_wait_time_seconds: 10
    sqs_visibility_timeout_seconds: 5

sleep_score_sqs_configuration:
    sqs_queue_name: dev_sleep_score_push
    sqs_max_connections: 50
    sqs_max_messages_read: 10
    sqs_wait_time_seconds: 20
    sqs_visibility_timeout_seconds: 120

dynamodb:
  region: us-east-1
  tables:
    app_stats: app_stats
    features: features
    sense_prefix : prod_sense #not used at the moment but we need it here
    calibration: calibration
    device_data: sense_data
    pill_data: pill_data
    online_hmm_models: online_hmm_models
    feature_extraction_models: feature_extraction_models
    ring_time_history: ring_history_by_account
    sleep_hmm: sleephmm
    sleep_score_parameters: sleep_score_parameters
    sleep_stats: sleep_stats
    timezone_history: timezone_history
  endpoints:
    app_stats: http://dynamodb.us-east-1.amazonaws.com
    features : http://dynamodb.us-east-1.amazonaws.com
    sense_prefix: http://dynamodb.us-east-1.amazonaws.com
    sense_last_seen : http://dynamodb.us-east-1.amazonaws.com
    calibration : http://dynamodb.us-east-1.amazonaws.com
    device_data: http://dynamodb.us-east-1.amazonaws.com
    pill_data: http://dynamodb.us-east-1.amazonaws.com
    online_hmm_models: http://dynamodb.us-east-1.amazonaws.com
    feature_extraction_models: http://dynamodb.us-east-1.amazonaws.com
    ring_time_history: http://dynamodb.us-east-1.amazonaws.com
    sleep_hmm: http://dynamodb.us-east-1.amazonaws.com
    sleep_score_parameters: http://dynamodb.us-east-1.amazonaws.com
    sleep_stats: http://dynamodb.us-east-1.amazonaws.com
    timezone_history: http://dynamodb.us-east-1.amazonaws.com

num_queue_producer_threads: 2
num_send_message_threads: 2

num_queue_consumer_threads: 2
num_compute_timeline_threads: 2

queue_producer_interval_minutes: 10

push_notification_configuration:
  endpoint: https://kinesis.us-east-1.amazonaws.com
  streams:
    push_notifications: dev_push_notifications